"""Planner agent responsible for sequencing study tasks."""

from __future__ import annotations

import re
from typing import Iterable

from ..models import LearningGoal, PlanItem
from .base import Agent


class PlannerAgent(Agent):
    """Agent that generates short task lists for a learning day."""

    def __init__(self, llm=None) -> None:
        super().__init__(
            name="planner",
            system_prompt=(
                "You are a structured learning planner. Produce concise task bullets "
                "for the given learning goal, focusing on observable actions."
            ),
            llm=llm,
        )

    def run(
        self,
        goal: LearningGoal,
        day_number: int,
        previous_items: Iterable[PlanItem] | None = None,
        reflection: str | None = None,
    ) -> list[dict[str, object]]:
        """Create plan suggestions for the day."""

        previous_summary = "\n".join(f"- {item.task}" for item in previous_items or [])
        reflection_text = reflection or "None"
        user_prompt = (
            f"Goal: {goal.title}\n"
            f"Day: {day_number}\n"
            f"Learner context: {goal.learner_profile or 'n/a'}\n"
            f"Reflection: {reflection_text}\n"
            f"Existing plan items:\n{previous_summary or '- none recorded'}\n"
            "Provide 3 concrete steps (max 20 words each)."
        )
        prompt = self.build_prompt(user_prompt)
        response = self.call_llm(prompt)
        tasks = self._parse_tasks(response)
        if not tasks:
            tasks = [
                "Review prior notes",
                "Learn a new concept",
                "Apply the concept via a quick project",
            ]
        return [
            {"task": task, "sequence": idx + 1, "notes": "generated by planner"}
            for idx, task in enumerate(tasks)
        ]

    @staticmethod
    def _parse_tasks(response_text: str) -> list[str]:
        """Extract bullet-like lines from the LLM response."""

        tasks: list[str] = []
        for line in response_text.splitlines():
            line = line.strip()
            if not line:
                continue
            match = re.match(r"^[\-\d\.)]+\s*(.+)$", line)
            if match:
                tasks.append(match.group(1).strip())
            elif len(line.split()) > 3:
                tasks.append(line)
        return tasks[:5]


__all__ = ["PlannerAgent"]
